### ISSUE TITLE
Question: Android?

### ISSUE THREAD

**Issue by nobodyguy** [b3dgs/warcraft-remake#2]
Hello, awesome work! How did you manage to run it on Android?

**Comment by TodorBalabanov** [comment]
I have problems to build it under Mac OS X. Do you have an idea what Maven command should I run?

**Comment by DjThunder** [comment]
For android, the only one difference with other target is the main (as described in the readme of https://github.com/b3dgs/lionengine):

```java
public final class AppAndroid extends Activity
{
    @Override
    protected void onPostCreate(Bundle savedInstanceState)
    {
        super.onPostCreate(savedInstanceState);

        Engine.start("AppAndroid", Version.create(1, 0, 0), this);
        final Resolution output = new Resolution(800, 480, 60);
        final Config config = new Config(output, 32, false);
        final Loader loader = new Loader(config);
        loader.start(Menu.class);
    }

    @Override
    public void finish()
    {
        super.finish();
        Engine.terminate();
    }
}
```

But I currently ran it only with Dalvik on my computer.
In this repository there is only the PC version for the moment (just change the main by yourself, and remember, it is a prototype for the moment, as a use case for my LionEngine).

About OSX, I also ran it with a virtual machine (the 10.6 version), with no special command (**mvn clean install**).
What kind of error do you encounter ?

**Comment by nobodyguy** [comment]
Thanks for the quick response!
I'll check LionEngine first. What about dependency on AWT? Do I need to change it too?

**Comment by DjThunder** [comment]
It is better to choose only one target (AWT, SWT, Android).

Be aware that if you use a mouse/keyboard implementation for the AWT/SWT module, it will not be available on Android. Gameplay has to be platform specific... which sounds logic :)

**Comment by nobodyguy** [comment]
Sure :-) I'm aware of this, but I was a bit confused because I didn't find any detailed info about it.
Thanks for all your info, I'll dig into this deeper and try to adjust code step by step.

**Comment by DjThunder** [comment]
Check the website: http://lionengine.b3dgs.com/ (multi lang on top right)

**Comment by nobodyguy** [comment]
Once again - awesome work! Thanks for that.

**Comment by TodorBalabanov** [comment]
Thanks for the fast reply. It seems that the problem is on my side. Some how I have missed to include engine in the build process. 

[ERROR] Failed to execute goal on project warcraft-game: Could not resolve dependencies for project com.b3dgs.warcraft:warcraft-game:jar:0.1.0-SNAPSHOT: The following artifacts could not be resolved: com.b3dgs.lionengine:lionengine-core-awt:jar:8.2.0-SNAPSHOT, com.b3dgs.lionengine:lionengine-core:jar:8.2.0-SNAPSHOT, com.b3dgs.lionengine:lionengine-audio-sc68:jar:8.2.0-SNAPSHOT, com.b3dgs.lionengine:lionengine-audio-wav:jar:8.2.0-SNAPSHOT, com.b3dgs.lionengine:lionengine-game:jar:8.2.0-SNAPSHOT: Could not find artifact com.b3dgs.lionengine:lionengine-core-awt:jar:8.2.0-SNAPSHOT -> [Help 1]

**Comment by DjThunder** [comment]
Ah, yes, this is because it is currently not on maven central.

You can convert the lib to a local maven artifact: https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

One day I will publish it on maven central.

**Comment by TodorBalabanov** [comment]
OK. Thanks. I will try to do it by this way.
